parameters:
#    templo.example.class: Templo\TemploBundle\Example

services:
    # custom file namer
    templo.namer_uniqid:
        class: Templo\TemploBundle\Namer\TemploNamer

    templo.form.oficina:
        class: Templo\TemploBundle\Form\OficinaType 
        tags:
            - { name: form.type, alias: oficina_form}
            
    templo.form.flow.oficina:
        class: Templo\TemploBundle\Form\OficinaFlow
        parent: craue.form.flow
        scope: request
        calls:
            - [setFormType, ["@templo.form.oficina"]]
