parameters:
#    templo.example.class: Templo\TemploBundle\Example

services:
    templo.advertisement.validator:
        class: Templo\TemploBundle\Util\AdvertisementValidator
        arguments: [@validator]
    
    # custom file namer
    templo.namer_uniqid:
        class: Templo\TemploBundle\Namer\TemploNamer

    twig.extension.templo:
        class: Templo\TemploBundle\Twig\Extension\TemploTwigExtension
        tags:
            - { name: twig.extension }
