user_dashboard:
    pattern: /dashboard
    defaults:  { _controller: TemploUserBundle:Default:dashboard }    
        
user_settings:
    pattern: /settings
    defaults:  { _controller: TemploUserBundle:Default:userSetting }
  

