parameters:
#    templo_user.example.class: Templo\UserBundle\Example

services:
    authentication_handler:
        class: Templo\UserBundle\Handler\AuthenticationHandler
        public: false
        arguments: [@router, @session, @translator, @security.context]


