vich_uploader:
    db_driver: orm
    storage: vich_uploader.storage.filesystem
    mappings:
        property_image:
            uri_prefix: /uploads/property
            upload_destination: %kernel.root_dir%/../web/uploads/property
            delete_on_remove: true
            delete_on_update: true
            namer: templo.namer_uniqid