vich_uploader:
    db_driver: orm
    storage: vich_uploader.storage.filesystem
    mappings:
        user_profile_image:
            uri_prefix: /uploads/users
            upload_destination: %kernel.root_dir%/../web/uploads/users
            delete_on_remove: true
            delete_on_update: true
            namer: templo.namer_uniqid