fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Templo\UserBundle\Entity\User

    from_email:
        address:        contact@temploconsulting.com
        sender_name:    TemploConsulting.com

    service:
        mailer: fos_user.mailer.twig_swift

    registration:
        confirmation:
            enabled:    true
            template:   TemploUserBundle:Registration:registration.email.twig

    resetting:
        email:
            template:  TemploUserBundle:Resetting:resetting.email.twig

    profile:
        form:
            type: bricks_user_profile