<?php

namespace Templo\TemploBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InmuebleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InmuebleRepository extends EntityRepository
{
     /**
     * find published Properties
     *
     * $options = array(
     *     'return_qb' => if true, reurn $qb object
     * )
     *
     * @param array $options array of parameters
     * @return multitype:
     */
    public function findPublished(array $options = array())
    {
        $em = $this->getEntityManager();

        $qb = $em->createQueryBuilder()
            ->select('p')
            ->from('TemploBundle:Inmueble', 'p')
            ->where('p.published = :published')
            ->setParameter('published', true)
        ;

        // order by published_at field
        $qb->orderBy('p.publishedAt', 'DESC');

        /**
         * return $qb object
         */
        if (array_key_exists('return_qb', $options) && $options['return_qb'] == true) {
            return $qb;
        }

        return $qb->getQuery()->getResult();
    }
    
}
