<?php

namespace Templo\TemploBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserStarsPropertyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserStarsPropertyRepository extends EntityRepository
{
}
